PROJECT = erlgate
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0

DEPS = cowboy nested
dep_cowboy = git https://github.com/ninenines/cowboy 2.15.0
dep_nested = git https://github.com/odo/nested master

REL_DEPS += relx
include erlang.mk
